<table border="0" cellpadding="0" cellspacing="0" width="100%" align="center">
	<tr>
		<td align="left" valign="middle" class="blackbreadcrumb"><a href="/default.htm"><img src="/images/white-a.gif" width="44" height="30" alt="The National Archives" align="middle" class="blackbreadcrumb" border="0"></a><td>
		
		<td align="left" valign="middle" class="blackbreadcrumb"><span class="bbreadcrumb">  </span><a href="/default.htm" class="bbreadcrumb">The National Archives home</a><span class="bbreadcrumb"> > </span><a href="/online/default.htm" class="bbreadcrumb">Education, Events & Exhibitions</a><span class="bbreadcrumb"> > </span><a href="/museumonline/default.htm" class="bbreadcrumb">Museum Online</a><span class="bbreadcrumb"> > </span><a href="/museumonline/exhibitions.htm" class="bbreadcrumb">Exhibitions</a><span class="bbreadcrumb"> > </span><a href="/Museumonline/spies/default.htm" class="bbreadcrumb">Secrets & Spies</a></td>
	</tr>
</table>
