<table width="239"  cellpadding="0" cellspacing="0" border="0">
	<tr>
	<td class="hometable" align="left" valign="top">
<h3 class="eventsheader">Events:</h3></td>
<td class="hometable" align="left" valign="top"><a href="../secretsandspies/insert%20url%20here.htm"><img src="images/bullet.gif" width="8" height="8" alt="" align="middle" border="0"> Event 1 link to go here</a><br>
<a href="../secretsandspies/insert%20url%20here.htm"><img src="images/bullet.gif" width="8" height="8" alt="" align="middle" border="0"> Event 2 link goes here</a>
	</td>
	</tr>
	</table>
